const foodItems = [
  {
    id: 1000,
    name: "Mixed Biryani",
    description: "A delightful combination of flavors in one pot.",
    price: 300,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/mixed_Biryani.jpg",
    cartImage: "./assets/dish_images/mixed_Biryani.jpg",
    category: "specials",
  },
  {
    id: 1001,
    name: "Munako Chicken",
    description: "Signature spicy chicken starter.",
    price: 300,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/munako_Chicken.jpg",
    cartImage: "./assets/dish_images/munako_Chicken.jpg",
    category: "specials",
  },

  // Biryani
  {
    id: 2000,
    name: "Veg Biryani",
    description: "Flavorful biryani cooked with fresh vegetables.",
    price: 140,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/veg_Biryani.jpg",
    cartImage: "./assets/dish_images/veg_Biryani.jpg",
    category: "biryani",
  },
  {
    id: 2001,
    name: "Dum Biryani",
    description: "Classic dum biryani made with aromatic spices.",
    price: 150,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/Dum_Biryani.jpg",
    cartImage: "./assets/dish_images/Dum_Biryani.jpg",
    category: "biryani",
  },
  {
    id: 2002,
    name: "Plain Biryani",
    description: "Simple and aromatic biryani with minimal spices.",
    price: 100,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/plane_Biryani.jpg",
    cartImage: "./assets/dish_images/plane_Biryani.jpg",
    category: "biryani",
  },
  {
    id: 2003,
    name: "Paneer Biryani",
    description: "Rich and flavorful biryani with paneer cubes.",
    price: 180,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/paneer_Biryani.jpg",
    cartImage: "./assets/dish_images/paneer_Biryani.jpg",
    category: "biryani",
  },
  {
    id: 2004,
    name: "Mushroom Biryani",
    description: "Aromatic biryani with fresh mushrooms.",
    price: 180,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/mushroom_Biryani.jpg",
    cartImage: "./assets/dish_images/mushroom_Biryani.jpg",
    category: "biryani",
  },

  // Starters
  {
    id: 3000,
    name: "Paneer 65",
    description: "Crispy and spicy paneer starter.",
    price: 180,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/paneer_65.jpg",
    cartImage: "./assets/dish_images/paneer_65.jpg",
    category: "starters",
  },
  {
    id: 3001,
    name: "Chicken 65",
    description: "A popular deep-fried chicken starter.",
    price: 200,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/chicken_65.jpg",
    cartImage: "./assets/dish_images/chicken_65.jpg",
    category: "starters",
  },
  {
    id: 3002,
    name: "Chilli Mushroom",
    description: "Spicy and tangy mushroom starter.",
    price: 170,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/chilli_Mushroom.jpg",
    cartImage: "./assets/dish_images/chilli_Mushroom.jpg",
    category: "starters",
  },
  {
    id: 3003,
    name: "Chilli Chicken",
    description: "Spicy and flavorful chicken starter.",
    price: 180,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/chilli_Chicken.jpg",
    cartImage: "./assets/dish_images/chilli_Chicken.jpg",
    category: "starters",
  },

  // Curries
  {
    id: 4000,
    name: "Paneer Butter Masala",
    description: "Creamy paneer curry with buttery tomato gravy.",
    price: 160,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/paneer_Butter_Masala.jpg",
    cartImage: "./assets/dish_images/paneer_Butter_Masala.jpg",
    category: "curries",
  },
  {
    id: 4001,
    name: "Bone Chicken Curry",
    description: "Spicy and flavorful bone chicken curry.",
    price: 170,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/bone_Chicken_Curry.jpg",
    cartImage: "./assets/dish_images/bone_Chicken_Curry.jpg",
    category: "curries",
  },
  {
    id: 4002,
    name: "Kaju Paneer Curry",
    description: "Rich curry made with kaju and paneer.",
    price: 200,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/kaju_Paneer_Curry.jpg",
    cartImage: "./assets/dish_images/kaju_Paneer_Curry.jpg",
    category: "curries",
  },
  {
    id: 4003,
    name: "Mushroom Curry",
    description: "Delicious curry with fresh mushrooms.",
    price: 170,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/mushroom_Curry.jpg",
    cartImage: "./assets/dish_images/mushroom_Curry.jpg",
    category: "curries",
  },

  // Fried Rice
  {
    id: 5000,
    name: "Veg Fried Rice",
    description: "Stir-fried rice with mixed vegetables.",
    price: 120,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/veg_Fried Rice.jpg",
    cartImage: "./assets/dish_images/veg_Fried Rice.jpg",
    category: "fired-rice",
  },
  {
    id: 5001,
    name: "Chicken Fried Rice",
    description: "Fried rice with succulent pieces of chicken.",
    price: 190,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/chicken_Friedrice.png",
    cartImage: "./assets/dish_images/chicken_Friedrice.png",
    category: "fired-rice",
  },
  {
    id: 5002,
    name: "Egg Fried Rice",
    description: "Classic fried rice with eggs.",
    price: 140,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/egg_Fried_Rice.jpg",
    cartImage: "./assets/dish_images/egg_Fried_Rice.jpg",
    category: "fired-rice",
  },
  {
    id: 5003,
    name: "Paneer Fried Rice",
    description: "Flavorful fried rice with paneer cubes.",
    price: 140,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/paneer_Fried_Rice.jpg",
    cartImage: "./assets/dish_images/paneer_Fried_Rice.jpg",
    category: "fired-rice",
  },

  // Meals
  {
    id: 6000,
    name: "Full Meals",
    description: "Combinations of all different rice and curries.",
    price: 120,
    typeof: "./assets/veg.svg",
    color: "text-green-600",
    image: "./assets/dish_images/full_Meals.jpg",
    cartImage: "./assets/dish_images/full_Meals.jpg",
    category: "meals",
  },
  {
    id: 6001,
    name: "Mini Meals",
    description: "Combinations of limited different rice and curries.",
    price: 80,
    typeof: "./assets/non-veg.svg",
    color: "text-red-600",
    image: "./assets/dish_images/mini_Meals.jpg",
    cartImage: "./assets/dish_images/mini_Meals.jpg",
    category: "meals",
  },
];
